---
- hosts: nautobot
  connection: local
  gather_facts: false
  tasks:
    - name: Run nautobot-sync
      import_role:
        name: nautobot-sync
      # debugger: always

- hosts: nautobot
  tasks:
    - name: Run avdbuilder
      import_role:
        name: avdbuilder
      vars:
        fabric_name: TEST-FABRIC
        site_names: ["DC1", "DC2"]
      # debugger: always

    - name: copy output to group_vars
      copy:
        src: "{{ item }}"
        dest: "group_vars/"
        owner: "emil"
        mode: 0600
      with_fileglob:
        - "avdbuilder_vars/*"
      delegate_to: localhost